---
- name: Check existing install
  register: postgresql_exporter_version_check
  failed_when: False
  changed_when: False
  check_mode: False
  shell: /usr/bin/postgresql-exporter --version 2>&1
  tags:
    - postgresql
    - postgresql-exporter

- name: Fact version change
  set_fact:
    postgresql_exporter_version_changed: "{{ postgresql_exporter_version_check.rc != 0 or (postgresql_exporter_version_check.stdout_lines is defined and postgresql_exporter_version not in postgresql_exporter_version_check.stdout_lines[0]) | bool }}"
  tags:
    - postgresql
    - postgresql-exporter

- name: Download release tarball
  when: postgresql_exporter_version_changed
  unarchive:
    src: "{{ postgresql_exporter_download }}"
    dest: /usr/local/src
    remote_src: True
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - postgresql
    - postgresql-exporter

- name: Copy exporter binary
  when: postgresql_exporter_version_changed and not ansible_check_mode
  notify:
    - Restart postgresql-exporter
  copy:
    src: "/usr/local/src/postgres_exporter-{{ postgresql_exporter_version }}.linux-amd64/postgres_exporter"
    dest: /usr/bin/postgresql-exporter
    remote_src: True
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - postgresql
    - postgresql-exporter

- name: Write default config
  notify:
    - Restart postgresql-exporter
  template:
    src: exporter/default.j2
    dest: /etc/default/postgresql-exporter
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - postgresql
    - postgresql-exporter

- name: Write service file
  notify:
    - Restart postgresql-exporter
  template:
    src: exporter/service.j2
    dest: /etc/systemd/system/postgresql-exporter.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - postgresql
    - postgresql-exporter

- name: Start postgresql-exporter service
  systemd:
    name: postgresql-exporter
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - postgresql
    - postgresql-exporter

- name: Remove install directory
  file:
    path: "/usr/local/src/postgres_exporter-{{ postgresql_exporter_version }}.linux-amd64"
    state: absent
  tags:
    - postgresql
    - postgresql-exporter

...
